In [1]:
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  23 & 26 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [8]:
vector = np.random.rand(10)
print("Vector ", vector)
print("Vector's shape", vector.shape)
matrix = np.array([[11, 14, 17], [23, 26, 26], [29, 32, 35]])
print("Matrix ", matrix)
print("Matrix' shape", matrix.shape)

Vector  [0.10013405 0.09172209 0.47507193 0.97578493 0.99094612 0.9552563
 0.08644437 0.93862173 0.64196337 0.11396229]
Vector's shape (10,)
Matrix  [[11 14 17]
 [23 26 26]
 [29 32 35]]
Matrix' shape (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [15]:
vector1 = np.round(vector, 2) + 10
print("New vector ", vector1)
matrix1 = matrix * 2
print("New matrix", matrix1)
vector2 = vector**2
print("Vector ** 2", vector2)

New vector  [10.1  10.09 10.48 10.98 10.99 10.96 10.09 10.94 10.64 10.11]
New matrix [[22 28 34]
 [46 52 52]
 [58 64 70]]
Vector ** 2 [0.01002683 0.00841294 0.22569334 0.95215622 0.98197421 0.9125146
 0.00747263 0.88101075 0.41211697 0.0129874 ]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 1х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [16]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [26]:
#1
result_matrix = np.dot(B, A)
display(result_matrix, result_matrix.shape)
#2
result_matrix2 = np.dot(result_matrix, C)
display(result_matrix2, result_matrix2.shape)
#3
result_matrix3 = np.dot(result_matrix, D)
display(result_matrix3, result_matrix3.shape)

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

(2, 2)

array([[0.5202],
       [0.2846]])

(2, 1)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])

(2, 2)


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [27]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [29]:
display(vector, vector.shape)
display(vector.T, vector.T.shape)

array([0.10013405, 0.09172209, 0.47507193, 0.97578493, 0.99094612,
       0.9552563 , 0.08644437, 0.93862173, 0.64196337, 0.11396229])

(10,)

array([0.10013405, 0.09172209, 0.47507193, 0.97578493, 0.99094612,
       0.9552563 , 0.08644437, 0.93862173, 0.64196337, 0.11396229])

(10,)

In [30]:
column_vector = np.expand_dims(vector, axis=1)
display(column_vector, column_vector.shape)

array([[0.10013405],
       [0.09172209],
       [0.47507193],
       [0.97578493],
       [0.99094612],
       [0.9552563 ],
       [0.08644437],
       [0.93862173],
       [0.64196337],
       [0.11396229]])

(10, 1)

In [31]:
column_vector.T

array([[0.10013405, 0.09172209, 0.47507193, 0.97578493, 0.99094612,
        0.9552563 , 0.08644437, 0.93862173, 0.64196337, 0.11396229]])

In [32]:
column_vector.T.T

array([[0.10013405],
       [0.09172209],
       [0.47507193],
       [0.97578493],
       [0.99094612],
       [0.9552563 ],
       [0.08644437],
       [0.93862173],
       [0.64196337],
       [0.11396229]])

Отже спочатку це не був повноцінний вектор, і став ним після оперціїї expand_dims